### ISSUE TITLE
Forecast starts yesterday 

### ISSUE THREAD

**Issue by haaino** [golles/ha-knmi#110]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

When reading the sensor weather.knmi_knmi I noticed that my forecast date starts from 1 day previous from current date and that the forecast date stops tomorrow. 
I was expecting that the forecast date would start from today and would end the day after tomorrow 

how I made a configuration mistake somewhere?

### Integration version

1.70

### Home Assistant version

Core 2023.12.2

### Python version

3.11

**Comment by golles** [comment]
Please provide more information like diagnostics file and screenshots and I would also like to get all attributes from the weather entity which you can get from the developer options, states screen. Thanks

**Comment by haaino** [comment]
![image](https://github.com/golles/ha-knmi/assets/98317278/17a5fedd-3a92-418e-a87a-b4eb9e9d0cc3)

Mind you. The actual date is 19-12-2023

**Comment by haaino** [comment]
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.12.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.6",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Amsterdam",
    "os_name": "Linux",
    "os_version": "6.1.63-haos",
    "supervisor": "2023.12.0",
    "host_os": "Home Assistant OS 11.2",
    "docker_version": "24.0.7",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "knmi": {
      "version": "1.7.0",
      "requirements": []
    },
    "afvalwijzer": {
      "version": "2023.06.01",
      "requirements": []
    },
    "hacs": {
      "version": "1.33.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "places": {
      "version": "v2.6.0",
      "requirements": []
    },
    "neerslag": {
      "version": "2022.07.07.1",
      "requirements": []
    },
    "holidays": {
      "version": "1.9.10",
      "requirements": [
        "python-dateutil>=2.8.2",
        "holidays>=0.35"
      ]
    },
    "auto_backup": {
      "version": "1.4.1",
      "requirements": []
    },
    "openweathermap_all": {
      "version": "0.0.1",
      "requirements": [
        "owm2json==0.1.89"
      ]
    },
    "bosch": {
      "version": "0.23.4",
      "requirements": [
        "bosch-thermostat-client==0.23.2"
      ]
    },
    "dyson_local": {
      "version": "1.3.6",
      "requirements": [
        "paho-mqtt"
      ]
    },
    "presence_simulation": {
      "version": "3.2",
      "requirements": []
    },
    "google_geocode": {
      "version": "0.1.9",
      "requirements": []
    },
    "better_thermostat": {
      "version": "1.4.0",
      "requirements": []
    },
    "miele": {
      "version": "0.1.19",
      "requirements": [
        "flatdict==4.0.1",
        "pymiele==0.1.7"
      ]
    },
    "alarmo": {
      "version": "v1.9.13",
      "requirements": []
    },
    "blitzortung": {
      "version": "1.0.1",
      "requirements": [
        "paho-mqtt>=1.5.0"
      ]
    },
    "ha_strava": {
      "version": "3.2.29",
      "requirements": [
        "aiohttp>=3.6.1",
        "voluptuous>=0.11.7"
      ]
    },
    "entities_calendar": {
      "version": "0.0.10",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "knmi",
    "name": "KNMI",
    "codeowners": [
      "@golles"
    ],
    "config_flow": true,
    "documentation": "https://github.com/golles/ha-knmi/blob/main/README.md",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/golles/ha-knmi/issues",
    "version": "1.7.0",
    "is_built_in": false
  },
  "data": {
    "config_entry": {
      "entry_id": "22ebfa034715aeaa92a0668e72ee5236",
      "version": 1,
      "domain": "knmi",
      "title": "KNMI",
      "data": {
        "name": "KNMI",
        "latitude": "**REDACTED**",
        "longitude": "**REDACTED**",
        "api_key": "**REDACTED**"
      },
      "options": {
        "binary_sensor": true,
        "sensor": true,
        "weather": true
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": null,
      "disabled_by": null
    },
    "data": {
      "plaats": "Maarn",
      "timestamp": "1703007783",
      "time": "19-12-2023 18:43",
      "temp": "8.7",
      "gtemp": "6.9",
      "samenv": "Lichte regen",
      "lv": "98",
      "windr": "West",
      "windrgr": "270",
      "windms": "3",
      "winds": "2",
      "windk": "5.8",
      "windkmh": "10.8",
      "luchtd": "1015.0",
      "ldmmhg": "761",
      "dauwp": "8.4",
      "zicht": "13",
      "verw": "Vandaag veel regen. Woensdag enkele buien en vrij veel wind",
      "sup": "08:42",
      "sunder": "16:30",
      "image": "buien",
      "d0weer": "bewolkt",
      "d0tmax": "9",
      "d0tmin": "6",
      "d0windk": "4",
      "d0windknp": "12",
      "d0windms": "6",
      "d0windkmh": "22",
      "d0windr": "W",
      "d0windrgr": "270",
      "d0neerslag": "0",
      "d0zon": "11",
      "d1weer": "regen",
      "d1tmax": "8",
      "d1tmin": "6",
      "d1windk": "3",
      "d1windknp": "8",
      "d1windms": "4",
      "d1windkmh": "15",
      "d1windr": "W",
      "d1windrgr": "270",
      "d1neerslag": "80",
      "d1zon": "30",
      "d2weer": "regen",
      "d2tmax": "11",
      "d2tmin": "7",
      "d2windk": "4",
      "d2windknp": "12",
      "d2windms": "6",
      "d2windkmh": "22",
      "d2windr": "W",
      "d2windrgr": "270",
      "d2neerslag": "90",
      "d2zon": "10",
      "alarm": "1",
      "alarmtxt": "Vandaag zijn er geen waarschuwingen. Donderdagmiddag en -avond gaat het hard waaien. Daarvoor is code geel van kracht. In het hele land kunnen zware windstoten rond 75 km/uur voorkomen. Langs de kust en op het IJsselmeer zijn er windstoten rond 90 km/uur mogelijk, aan de noordkust tot 100 km/uur. De wind komt uit het noordwesten.  In de avond beperken de zware windstoten zich tot de kustgebieden. In de nacht naar vrijdag komt er langzaam minder wind, maar blijven er langs de kust zware windstoten mogelijk."
    }
  }
}

**Comment by haaino** [comment]
Perhaps I'm not fully understanding the weather.knmi forecast attributes

I was expecting that when I request forecast[1].temp for example, I would get the value for tomorrow's temperature. 

But it seems I'm mistaken in this?

Can you help me understand what I'm looking at. If I look at the values of forecast[0] they "fit" the weather of yesterday. Looking at forecast[1] they "fit" the weather of today. 
That makes me a little confused.

**Comment by golles** [comment]
`forecast[0]` is today, `forecast[1]` is tomorrow and `forecast[2]` is the day after tomorrow

**Comment by haaino** [comment]
Thx.

**Comment by HiDiHo01** [comment]
just dont use UTC and you get the correct date/time

_forcast method
today = dt.now(timezone).replace(hour=0, minute=0, second=0, microsecond=0)

eather.knmi:
  forecast:
    - datetime: "2023-12-20T00:00:00+01:00"
      condition: cloudy
      templow: 8
      temperature: 10
      precipitation_probability: 21
      wind_bearing: 270
      wind_speed: 50
      wind_speed_bft: 6
      sun_chance: 12
    - datetime: "2023-12-21T00:00:00+01:00"
      condition: rainy
      templow: 7
      temperature: 11
      precipitation_probability: 100
      wind_bearing: 270
      wind_speed: 26
      wind_speed_bft: 4
      sun_chance: 20
    - datetime: "2023-12-22T00:00:00+01:00"
      condition: rainy
      templow: 6
      temperature: 9
      precipitation_probability: 90
      wind_bearing: 270
      wind_speed: 22
      wind_speed_bft: 4
      sun_chance: 30

**Comment by haaino** [comment]
Thank you!!🙏
