### ISSUE TITLE
deprecated constant in 2024.1

### ISSUE THREAD

**Issue by Mariusthvdb** [golles/ha-knmi#111]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

as title, needs a new constant

### Integration version

1.7.0

### Home Assistant version

2024.1

### Python version

3.11.6

### Home Assistant log

```shell
Logger: homeassistant.const
Source: helpers/deprecation.py:204
First occurred: 00:16:57 (10 occurrences)
Last logged: 00:17:09

LENGTH_KILOMETERS was used from knmi, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.KILOMETERS instead, please create a bug report at https://github.com/golles/ha-knmi/issues
PRESSURE_HPA was used from knmi, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPressure.HPA instead, please create a bug report at https://github.com/golles/ha-knmi/issues
SPEED_KILOMETERS_PER_HOUR was used from knmi, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfSpeed.KILOMETERS_PER_HOUR instead, please create a bug report at https://github.com/golles/ha-knmi/issues
```

**Comment by golles** [comment]
Thanks, if I'm not mistaken these are warnings, right?

I did see the blog post a couple of days ago, https://developers.home-assistant.io/blog/2023/12/19/constant-deprecation/

I will update these somewhere later next year, as there is plenty of time till 2025.1 :-)

**Comment by Mariusthvdb** [comment]
yeah, but these warnings are very ugly... so please dont wait until 2025.1 ......

Fijne jaarwisseling !

**Comment by golles** [comment]
Main branch has the fix, next version release will get it soon
