### ISSUE TITLE
Zonkracht current and forecast?

### ISSUE THREAD

**Issue by nlmaca** [golles/ha-knmi#121]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The request

Is it possible to add current zonkracht and forecast value? That is available in the free API (v2) You can find it in the API as "gr"

**Comment by golles** [comment]
Please see #120
I hope to release that in the coming days

**Comment by golles** [comment]
@nlmaca I've been running #120 now for a day and it looks pretty stable. If you have the capability, you could try this out. I've also added `solar_irradiance` to the hourly forecast service.

**Comment by nlmaca** [comment]
I didn't know where to download your code, so i just downloaded your latest commit.

1. Tell new users that an API key from weerlive is needed to activate the integration ( i already had it, but couldn't find it in the readme.
2. all sensors were disabled in HA en i had to enable them

So far so good, only missing the forecast 'Globale stralingsintensiteit

**Comment by dutch-erik** [comment]
@golles I've installed V2 as well, looks good!

I see more pre-defined sensors than in previous version ;) , may I ask for one additional one: 
 - windrgr

I would like to see the windspeed in beaufort, although I see the option in your code, I'm not able to select it, see below:
 
![afbeelding](https://github.com/golles/ha-knmi/assets/62548287/73876e29-8a83-4961-afda-861faba3d67d)

**Comment by golles** [comment]
> @golles I've installed V2 as well, looks good!
> 
> I see more pre-defined sensors than in previous version ;) , may I ask for one additional one:
> 
> * windrgr
> 
> I would like to see the windspeed in beaufort, although I see the option in your code, I'm not able to select it, see below:
> 
> ![afbeelding](https://private-user-images.githubusercontent.com/62548287/306982035-73876e29-8a83-4961-afda-861faba3d67d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MDY3MDMsIm5iZiI6MTcwODYwNjQwMywicGF0aCI6Ii82MjU0ODI4Ny8zMDY5ODIwMzUtNzM4NzZlMjktOGE4My00OTYxLWFmZGEtODYxZmFiYTNkNjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDEyNTMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmOTNiODg2MWFjYmRmNzQwZWY0N2I4YzBmYWE2NDQxYTUzZjAwMjU0OTk0MDc3ZGQwYzk5MzkzYWQyZTQyNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yGnUlM2Lj--tWcew1f38jPCNBnLNs5m9iNbvSQMlJOk)

I am not sure why you replied to this issue, as it's not related...

Since HA can't convert those, I've added them as attributes to the wind sensor.

<img width="551" alt="Scherm­afbeelding 2024-02-22 om 13 53 51" src="https://github.com/golles/ha-knmi/assets/2211503/90e75fcd-05b2-4f33-aeb7-710da9b08f30">

**Comment by golles** [comment]
> I didn't know where to download your code, so i just downloaded your latest commit.
> 
> 1. Tell new users that an API key from weerlive is needed to activate the integration ( i already had it), but couldn't find it in the readme.
> 2. all sensors were disabled in HA and i had to enable them
> 
> So far so good, only missing the forecast 'Globale stralingsintensiteit

1. Users will see this when they add the integration:
<img width="468" alt="Scherm­afbeelding 2024-02-22 om 16 11 30" src="https://github.com/golles/ha-knmi/assets/2211503/22d98db3-3921-4576-ac08-d8960d43aba2">

2. This is covered in the new readme: https://github.com/golles/ha-knmi/blob/api-v2/README.md#entities

To get the forecast solar values, you need to call the service, see line 10 and 18 in the response
<img width="1220" alt="Scherm­afbeelding 2024-02-22 om 16 10 27" src="https://github.com/golles/ha-knmi/assets/2211503/d43af372-e616-4d3d-ba6a-ca07e2a341b4">

**Comment by nlmaca** [comment]
Thx. Will a take a look at how to create a card from a service. Have never used it. But i see the data. Thx for adding it!

**Comment by golles** [comment]
#120 has been released as version `2.0.0`
