### ISSUE TITLE
'knmi' sets "version" directly to update a config entry

### ISSUE THREAD

**Issue by Mariusthvdb** [golles/ha-knmi#122]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

thanks for the update,
please see new issue

### Integration version

2.0.0

### Home Assistant version

2024.3.0.dev20240225

### Python version

3.12.2

### Home Assistant log

```shell
Logger: homeassistant.helpers.frame
Bron: helpers/frame.py:133
First occurred: 23:00:08 (1 gebeurtenissen)
Laatst gelogd: 23:00:08

Detected that custom integration 'knmi' sets "version" directly to update a config entry. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to use async_update_entry instead at custom_components/knmi/__init__.py, line 102: config_entry.version = 2, please create a bug report at https://github.com/golles/ha-knmi/issues
```

**Comment by golles** [comment]
I'm aware of this, but have to do this still as 2024.2 doesn't allow me to set the version with `hass.config_entries.async_update_entry(config_entry, version=2)`, I've already have this documented in code: https://github.com/golles/ha-knmi/blob/main/custom_components/knmi/__init__.py#L99-L102

**Comment by Mariusthvdb** [comment]
nice, my pardon, I didnt check the code.....

**Comment by golles** [comment]
> nice, my pardon, I didnt check the code.....

No worries, this issue is a good reminder to not forget this, so thanks for creating this!
