### ISSUE TITLE
API provides hourly neerslag in mm, yet reported incorrectly in HA as %

### ISSUE THREAD

**Issue by nonplusnl** [golles/ha-knmi#126]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

The Weerlive API reports neerslag as % per day, but in mm per hour. However, the KNMI integration appears to report also the hourly neerslag as %, not as mm. 
How to reproduce: when configuring a weather card to show precipitation probability, the card shows the numbers reported by the API, appended by "%" instead of "mm". When configuring weather card to report precipitation amount, the card does not report anything.

### Integration version

2.0.0

### Home Assistant version

core-2024.2.5

### Python version

3.12

**Comment by golles** [comment]
Thanks for reporting!

> The Weerlive API reports neerslag as % per day, but in mm per hour. However, the KNMI integration appears to report also the hourly neerslag as %, not as mm.

I've got a PR with a fix ready that should set the correct value for hourly forecasts, please test

> How to reproduce: when configuring a weather card to show precipitation probability, the card shows the numbers reported by the API, appended by "%" instead of "mm". When configuring weather card to report precipitation amount, the card does not report anything.

How do you configure a (which?) weather card to show precipitation amount?

**Comment by nonplusnl** [comment]
Check, the fix works, thanks! 
Below you see precipitation in mm for hourly forecasts (in two different weather cards), and in the bottom card, the daily forecast where Weerlive provides probabilities
![image](https://github.com/golles/ha-knmi/assets/21319667/4faa155e-fae2-4651-af59-da55290a1ec7)
