### ISSUE TITLE
Question: is hourly response KNMI oke?

### ISSUE THREAD

**Issue by haaino** [golles/ha-knmi#131]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The request

I noticed that when you do an hourly request the response for **precipitation_probability** of the service weather.knmi_knmi  is for me somewhat unexpected (see response below).

I wonder if this result should be multiplied by 10 or not?

  forecast:
    - datetime: "2024-03-11T12:00:00+01:00"
      condition: pouring
      temperature: 7
      **precipitation_probability: 0.3**
      wind_bearing: 336
      wind_speed: 3
      wind_speed_bft: 1
      solar_irradiance: 39
    - datetime: "2024-03-11T13:00:00+01:00"
      condition: pouring
      temperature: 7
      **precipitation_probability: 0.5**
      wind_bearing: 4
      wind_speed: 7
      wind_speed_bft: 2
      solar_irradiance: 55z

**Comment by golles** [comment]
If I understand correctly, #126 should resolve this

**Comment by haaino** [comment]
Sorry I missed it. 

Thanks
