### ISSUE TITLE
Intermittent false "Snowy" state

### ISSUE THREAD

**Issue by vincentwolsink** [golles/ha-knmi#132]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

Since 2.0.0 I've seen the status "snowy" popup intermittently and disappear after 10 minutes (probably after the next update). Checking weerlive.nl at that time does not show snowy as current weather.

Weird thing is it doesn't explicitly change to snowy in the log, but it is visible in the history graph. Looks like a failure to get the correct data. I don't see any related errors/warnings in the log at the time.

![Screenshot 2024-03-11 at 15 16 38](https://github.com/golles/ha-knmi/assets/1639734/89841e49-6cf0-406e-bd6c-24a87bbfba78)

### Integration version

2.0.0

### Home Assistant version

core-2024.3.0

### Python version

3.12.2

### Diagnostics

I will try to get it while it shows as snowy. But since it is a short timeframe and happens intermittently it will be difficult :)

**Comment by vincentwolsink** [comment]
I agree this kind of logic should not be in the integration. Lets wait for an upstream fix then. Thanks!

**Comment by hmmbob** [comment]
Ah, just came here to report the same issue:

![image](https://github.com/golles/ha-knmi/assets/33529490/5849c813-42d7-43e9-90da-8cc50034289d)

I guess it is unlikely that it'll be snowy with >10C outside ;-)

**Comment by M20Lucas** [comment]
For me here in Mierlo, it has been ‘snowy’ way longer that just one interval in between calls to the api. 
![IMG_0198](https://github.com/golles/ha-knmi/assets/104757223/3b8ebc63-7981-4dc0-937d-9653fb60cb02)

**Comment by golles** [comment]
I've also seen this a lot more recently.
I did start on a workaround but haven't got the time to finalize it.
I do have the response JSON where this happens, maybe you can also confirm that the `samenv` field (or `Omschrijving` sensor) is set to `Motregen of motsneeuw` when this is happening.
Thanks

**Comment by M20Lucas** [comment]
I can confirm:

![IMG_0200](https://github.com/golles/ha-knmi/assets/104757223/23ecb16e-494f-4df4-900d-c76cda571844)

**Comment by golles** [comment]
Thanks 🙏

**Comment by hmmbob** [comment]
![image](https://github.com/golles/ha-knmi/assets/33529490/05953b94-8408-4af8-b589-ef7c78c22d8f)
Same here

**Comment by M20Lucas** [comment]
Not sure if this is related:
In the ‘omschrijving’ it also says `Regen.` instead of just `Regen` (and to be clear it is actually raining outside). Couldn’t find it in the translation file, so I figured it has to do with the API as well?

![IMG_0202](https://github.com/golles/ha-knmi/assets/104757223/f265b9b0-fcc3-4859-bafa-10cf179873d9)
