### ISSUE TITLE
Zonkracht sensors

### ISSUE THREAD

**Issue by hmmbob** [golles/ha-knmi#139]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The request

I'd like to have the KNMI "zonkracht" information available as sensor. Example from the KNMI homepage:

![image](https://github.com/golles/ha-knmi/assets/33529490/dfc411fc-eb8e-41a9-9efd-a1c964fd1fad)

### Additional information

I currently have OpenUV setup to warn about high UV intensity - however it does not take the cloud cover into account at all. For example, it's warning me for level 5 right now - while all I see  outside is grey clouds. Looks like the KNMI information (on their website) is more accurate.

I did notice the `solar_irradiance` sensor, but that's not what I mean. 

I did see https://github.com/golles/ha-knmi/issues/121, which refers to version 2.0 but I can't find the info in 2.0.

**Comment by golles** [comment]
Hi, the Weerlive API doesn't have UV information available. You could ask them if they have it and are willing to expose it in their v2 API. Once it's there it can be added in this integration.

The `solar_irradiance` is an energy-related sensor (useful if you have solar panels) while uv is about light intensity, as far as I could find, you can't covert one to another, see this question: https://www.natuurkunde.nl/vraagbaak/11368/uv-straling-zonnestraling

**Comment by hmmbob** [comment]
> Hi, the Weerlive API doesn't have UV information available. You could ask them if they have it and are willing to expose it in their v2 API. Once it's there it can be added in this integration.

Asked via mail, keep you posted.

**Comment by hmmbob** [comment]
For those interested, I am now calculating / estimating the real zonnekracht with the following template sensor, based on [FAQ at OpenUV](https://www.openuv.io/dashboard?tab=4):

```yaml
template:
  - trigger:
      - platform: state
        entity_id:
          - sensor.openuv_current_uv_index
          - sensor.knmi_omschrijving
    sensor:
      - name: "Calculated UV"
        state: >-
          {% set rawUV = states('sensor.openuv_current_uv_index') | float %}
          {% set factor = 1 %}
          {% if states('sensor.knmi_omschrijving') in ("Onbewolkt") %}
            {% set factor=1 %}
          {% elif states('sensor.knmi_omschrijving') in ("Licht bewolkt")%}
            {% set factor=0.89 %}
          {% elif states('sensor.knmi_omschrijving') in ("Half bewolkt")%}
            {% set factor=0.73 %}
          {% elif states('sensor.knmi_omschrijving') is search("regen", ignorecase=True) or 
                  states('sensor.knmi_omschrijving') is search("onweer", ignorecase=True) or
                  states('sensor.knmi_omschrijving') in ("Geheel bewolkt","Zwaar bewolkt") %}
              {% set factor=0.31 %}
          {% endif %}
          {{ (rawUV * factor) | round(0) }}
        # Factors obtained from https://www.openuv.io/dashboard?tab=4
```

**Comment by hmmbob** [comment]
> > Hi, the Weerlive API doesn't have UV information available. You could ask them if they have it and are willing to expose it in their v2 API. Once it's there it can be added in this integration.
> 
> Asked via mail, keep you posted.

![image](https://github.com/golles/ha-knmi/assets/33529490/a5fdb443-2c7b-4dca-b41e-19d5c1a0bbd8)
