### ISSUE TITLE
Weather forecast always displays minimum temperature

### ISSUE THREAD

**Issue by silvanverschuur** [golles/ha-knmi#14]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

The weather forecast always displays the minimum temperature instead of min/max.

![image](https://user-images.githubusercontent.com/3354864/148637608-c82032cb-f4f8-4693-848e-9def853b7d7a.png)

Screenshot of KNMI website:

![image](https://user-images.githubusercontent.com/3354864/148637621-a862d337-078a-430b-8a00-65d1ac08e8d5.png)

### What version of this integration has the issue?

1.1.5

### What version of Home Assistant Core has the issue?

2021.12.7

**Comment by golles** [comment]
I see I made a copy paste mistake in my previous PR, https://github.com/golles/ha-knmi/pull/13/files#diff-0f42a2a6915296d25ab636ec9223c640a71c87276c99a984f72942e1c58b8561R118-R119

Will have a fix ready soon

**Comment by golles** [comment]
I've released 1.1.6 with a fix for this, thanks for sharing your feedback!

**Comment by silvanverschuur** [comment]
It's working again, thanks!
