### ISSUE TITLE
sensor.knmi_omschrijving adds period ( . ) after "Regen" but not with others

### ISSUE THREAD

**Issue by hmmbob** [golles/ha-knmi#140]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

Well, the subject says it all 😄 

![image](https://github.com/golles/ha-knmi/assets/33529490/caa7538d-a994-4bca-bd72-6de857541d54)
![image](https://github.com/golles/ha-knmi/assets/33529490/4c0ca582-3f5d-4001-ae83-67a1f81d17dc)

### Integration version

2.0.1

### Home Assistant version

core-2024.4.4

### Python version

3.12

**Comment by golles** [comment]
Will raise this with the supplier, as this is directly coming from the API, and the field `samenv` is been taking directly from there

**Comment by hmmbob** [comment]
Looking in the history, this is still happening

**Comment by hmmbob** [comment]
Not stale

**Comment by golles** [comment]
I contacted the supplier today to address this issue. Apologies for the delay; I was dealing with some distractions. The problem has been addressed, and we should monitor the situation over the coming days to ensure it has been resolved.

**Comment by hmmbob** [comment]
Thanks!

**Comment by hmmbob** [comment]
Solved!
