### ISSUE TITLE
Update failed! - Expecting value: line 1

### ISSUE THREAD

**Issue by Mariusthvdb** [golles/ha-knmi#144]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

there is not a lot of info here, so Ill just post it as is.

it does not happen too frequently but still I occurred a few times now, so I believe an issue is useful

### Integration version

2.1.0

### Home Assistant version

2024.5.2

### Python version

3.12

### Home Assistant log

```shell
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.knmi
Bron: custom_components/knmi/coordinator.py:49
integratie: KNMI (documentatie, problemen)
Eerst voorgekomen: 16:28:25 (1 gebeurtenissen)
Laatst gelogd: 16:28:25

Update failed! - Expecting value: line 1 column 54 (char 53)
```

### Additional information

will check if `custom_components.knmi: debug` provides more info  in the logs

**Comment by golles** [comment]
Please provide the diagnostic file from when this happens, that file has the actual JSON response in there and we can see what's going on.

I think there was just a problem with the weerlive server, as I have also a failed update around the same time.

**Comment by Mariusthvdb** [comment]
yes that could well be it, but, given that is not that unique an issue... shouldnt the integration catch that?

**Comment by Mariusthvdb** [comment]
just downloaded the new version, will keep an eye out for it, if not Ill close
