### ISSUE TITLE
Weather data not correct (location)

### ISSUE THREAD

**Issue by martijntenpas** [golles/ha-knmi#145]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

I have provided the configuration with the LAT / LON data from my location. The data in Home Assistant is not the same as the data I find on "weerlive" for the same location (city). I see some other value's at max temperature / air pressure.

Data in HA
![image](https://github.com/golles/ha-knmi/assets/84871327/0eae8050-e97f-41cc-9b37-90b4b241de9d)

Data on Weerlive
![image](https://github.com/golles/ha-knmi/assets/84871327/cf6e43ab-f380-41e3-ae6a-f07ac5dd1af1)

Hourly forecast
![image](https://github.com/golles/ha-knmi/assets/84871327/ba35ec52-f934-44a9-936f-16cf64c9562d)

### Integration version

2.1.0

### Home Assistant version

2024.5.2 / 12.3

### Python version

3.11.8

**Comment by golles** [comment]
Can you please provide your diagnostics file as well, that will make it easier to investigate

**Comment by martijntenpas** [comment]
Sure! 
[config_entry-knmi-29ad1f977f6c674ee403f306d3954a75.json](https://github.com/golles/ha-knmi/files/15292784/config_entry-knmi-29ad1f977f6c674ee403f306d3954a75.json)

**Comment by golles** [comment]
When I look at the json data (parsed and raw) from the diagnostics file you provided the max temp for today is `24`
```json
...
      "wk_verw": [
        {
          "dag": "13-05-2024",
          "image": "regen",
          "max_temp": 24,
          "min_temp": 16,
        }
...
```
While indeed looking into the hourly forecast, the "current hour" is `24` while a few upcoming hours have `25`:
```json
...

      "uur_verw": [
        {
          "uur": "13-05-2024 12:00",
          "timestamp": 1715594400,
          "image": "zonnig",
          "temp": 24,
          ...
        },
        {
          "uur": "13-05-2024 13:00",
          "timestamp": 1715598000,
          "image": "zonnig",
          "temp": 25,
          ...
        },
        {
          "uur": "13-05-2024 14:00",
          "timestamp": 1715601600,
          "image": "halfbewolkt",
          "temp": 25,
          ...
        },
        {
          "uur": "13-05-2024 15:00",
          "timestamp": 1715605200,
          "image": "zonnig",
          "temp": 25,
          ...
        },
        {
          "uur": "13-05-2024 16:00",
          "timestamp": 1715608800,
          "image": "bewolkt",
          "temp": 25,
          ...
        },
        {
          "uur": "13-05-2024 17:00",
          "timestamp": 1715612400,
          "image": "regen",
          "temp": 22,
          ...
        },
...
```

Since the value is taken from the API, I'll need to report this to the API supplier

**Comment by martijntenpas** [comment]
Dankje Sander, we wachten af!

**Comment by golles** [comment]
I contacted the supplier today to address this issue. Apologies for the delay; I was dealing with some distractions. The problem has been addressed, and we should monitor the situation over the coming days to ensure it has been resolved.

**Comment by golles** [comment]
This is still an issue:
<img width="550" alt="Scherm­afbeelding 2024-06-28 om 14 59 32" src="https://github.com/golles/ha-knmi/assets/2211503/f01c1a22-aff9-47b7-bdfd-d0a9f0703fa9">

<img width="444" alt="Scherm­afbeelding 2024-06-28 om 14 59 43" src="https://github.com/golles/ha-knmi/assets/2211503/469683af-dfbb-41fe-a8d0-983844b97a63">

Also interesting to see the max temp sensor is changing from 17/19 often

**Comment by Yasp0** [comment]
Is it me or is this still an issue?  

sensor.knmi_max_temperature_today says 30.

When I check on https://weerlive.nl/ for my city it says 26 degrees is the max.

**Comment by golles** [comment]
The problem is that the API is giving a fluctuating value over time for this; this is what it does for me:

<img width="551" height="314" alt="Image" src="https://github.com/user-attachments/assets/342549a4-02ad-474e-8adb-199c106f9bce" />

Very often there is a 4 degrees (C) bounce
