### ISSUE TITLE
Strange values knmi_globale_stralingsintensiteit sensor

### ISSUE THREAD

**Issue by HiDiHo01** [golles/ha-knmi#148]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

At the start and end of the day knmi_globale_stralingsintensiteit gives a strange value of 523

### Integration version

2.1.0

### Home Assistant version

every

### Python version

3.12

**Comment by golles** [comment]
<img width="1409" alt="Scherm­afbeelding 2024-05-24 om 12 29 39" src="https://github.com/golles/ha-knmi/assets/2211503/35920e00-d421-41d0-9256-4e16c325c547">

This is an issue in the API, I'll contact the supplier. To manage expectations, there is not much this component can do about this

**Comment by HiDiHo01** [comment]
If this cant be fixed by the supplier, you could make value 253 to never return a value

**Comment by golles** [comment]
I contacted the supplier today to address this issue. Apologies for the delay; I had some distractions. The problem should now be resolved, and we shouldn't see a similar spike tomorrow around sunrise.

**Comment by mcmd1962** [comment]
Yesterday (June 27) I saw suddenly 2 consecutive peaks in the morning, this morning I saw no early morning peak anymore. Thanks for addressing this issue.

**Comment by Toon83** [comment]
![Schermafbeelding 2024-07-04 151818](https://github.com/golles/ha-knmi/assets/123402778/ca54b807-7580-48f2-987c-682dec76bef5)
The 523 watt spikes seem to have returned.
I also contacted the KNMI about this, but they didn't see something similar on their end and pointed towards weerlive.nl for this.

**Comment by HiDiHo01** [comment]
Problem has never been gone
