### ISSUE TITLE
Weather condition "_" can't be mapped

### ISSUE THREAD

**Issue by haaino** [golles/ha-knmi#149]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

I noticed a '_' in the condition field

### Integration version

2.1.0

### Home Assistant version

HA 2024.5.3

### Python version

3.12

### Home Assistant log

```shell
This error originated from a custom integration.

Logger: custom_components.knmi
Source: custom_components/knmi/weather.py:114
integration: KNMI (documentation, issues)
First occurred: 09:21:05 (81 occurrences)
Last logged: 11:00:35

Weather condition "_" can't be mapped, please raise a bug
```

**Comment by golles** [comment]
Please provide the logs from the log file and add diagnostics so I can have a look what is going on

**Comment by haaino** [comment]
Unfortunately for the issue, the issue has resolved itself. Now the condition field is filled with text again.

The content of the log file is in the issue description, but I do not have the diagnostics data. I do not know whether or not I can still retrieve this info somewhere else?

The only thing I see is:"2024-05-24 09:24:05.227 ERROR (MainThread) [custom_components.knmi] Weather condition "_" can't be mapped, please raise a bug"

When it happens again, I will try to gather as much info as possible.

**Comment by golles** [comment]
Now I think about it, `_` or `-` is usually meaning that the data is not known, I will add it to that function.
