### ISSUE TITLE
Temperature Sensor Values Fluctuate Wildly

### ISSUE THREAD

**Issue by Zendio** [golles/ha-knmi#154]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

The sensor values for temperature are fluctuating strangely. Sometimes they are correct, but in the next update, they jump to a value that doesn't correspond to reality. Additionally, there are times when the temperature doesn't update at all, despite having enough API calls remaining. This issue has only been occurring for a few days, and I cannot determine the cause.

### Integration version

2.1.0

### Home Assistant version

core-2024.5.5

### Python version

3.12.2

### Home Assistant log

[home-assistant_knmi_2024-06-05T11-20-43.122Z.log](https://github.com/user-attachments/files/15586165/home-assistant_knmi_2024-06-05T11-20-43.122Z.log)

### Diagnostics

[config_entry-knmi-e065de00bcfc7a9f8e638d9fb4c4c6e5.json](https://github.com/user-attachments/files/15586162/config_entry-knmi-e065de00bcfc7a9f8e638d9fb4c4c6e5.json)

### Additional information

![CleanShot 2024-06-05 at 11 38 16](https://github.com/golles/ha-knmi/assets/5435734/09043e70-34ee-4059-aada-d8e61d6a6f48)
![CleanShot 2024-06-05 at 11 38 49](https://github.com/golles/ha-knmi/assets/5435734/a3a3a985-051f-4289-9c45-bcf6a15e1ab9)

**Comment by golles** [comment]
Please provide logs and diagnostics

**Comment by Zendio** [comment]
[home-assistant_knmi_2024-06-05T11-20-43.122Z.log](https://github.com/user-attachments/files/15586065/home-assistant_knmi_2024-06-05T11-20-43.122Z.log)

**Comment by Zendio** [comment]
> Please provide logs and diagnostics

Added to the main post.

**Comment by Zendio** [comment]
![CleanShot 2024-06-06 at 08 01 46](https://github.com/golles/ha-knmi/assets/5435734/e1cf32d0-2ef6-4c0f-aa7c-9c0d4b757b1d)
It seems to be working properly again.

**Comment by Zendio** [comment]
![CleanShot 2024-06-06 at 08 01 46](https://github.com/golles/ha-knmi/assets/5435734/e1cf32d0-2ef6-4c0f-aa7c-9c0d4b757b1d)
It seems to be working properly again.

**Comment by Toon83** [comment]
![image](https://github.com/golles/ha-knmi/assets/123402778/690c155b-7c00-49a5-acda-d56ca7b3d199)

It still fluctuates heavily sometimes.

**Comment by Toon83** [comment]
Don't know what is going on today, but Air pressure, Humidity, Temperature, Wind speed and Visibility all seem to fluctuate like crazy. And Solar irradiance seems completely broken since last night.

![Schermafbeelding 2024-07-20 212230](https://github.com/user-attachments/assets/c0706b3e-0ab5-42ff-908e-69aa8fec7971)

**Comment by Zendio** [comment]
I haven't had problems in quite some time, but here's the comment preventing the issue from closing.

**Comment by Toon83** [comment]
Well, the situation seems to have improved. But yesterday at 07:41, 08:11 and 08:41, and today at 07:21, 10:21, 11:21 and 13:21 are still some things that don't look quite right to me.
![Schermafbeelding 2024-08-20 195402](https://github.com/user-attachments/assets/985db2eb-ec09-4331-943f-f17809a706d5)
Sure, in weather things can fluctuate. But not in this fashion.

**Comment by Toon83** [comment]
Again some spikes at 13, 14 and 15 September.

![Schermafbeelding 2024-09-17 200450](https://github.com/user-attachments/assets/1fa29b4c-cea7-41d8-8e6a-f2ec538d5063)
