### ISSUE TITLE
The given API key is invalid

### ISSUE THREAD

**Issue by DavidVankan** [golles/ha-knmi#161]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

after installation i add it to my intergration.
it asks me to get a free Aoi Key.. 
Idid get te apo key in my mail and i activated the acount.

if i add the name and the api key i get : The given API key is invalid

i waited 1 hour and still same error

### Integration version

2.2.0.

### Home Assistant version

core-2024.10.2

### Python version

3.12.4

### Home Assistant log

```shell
This error originated from a custom integration.

Logger: custom_components.knmi
Source: custom_components/knmi/config_flow.py:52
integration: knmi (documentation, issues)
First occurred: 2:27:16 PM (10 occurrences)
Last logged: 2:56:20 PM

The given API key is invalid
```

### Diagnostics

```json
nvt
```

### Additional information

nvt

**Comment by golles** [comment]
My first impression is that something is wrong with your key. Are you sure you copied it without anything extra, eg spaces?

What happens if you open the following link, and replace `YOURKEY` with your key: https://weerlive.nl/api/weerlive_api_v2.php?locatie=Amsterdam&key=YOURKEY

**Comment by ronaldb73** [comment]
I have the same issue. 
https://weerlive.nl/api/weerlive_api_v2.php?locatie=Amsterdam&key=YOURKEY (replaced API Key) gives: 
{ "liveweer": [{"fout": "Vraag eerst een API-key op, zie http://weerlive.nl/delen.php"}]}

**Comment by Servizio-R** [comment]
I have the same issue, opening : https://weerlive.nl/api/weerlive_api_v2.php?locatie=Amsterdam&key=YOURKEY 
gives me this response... 
{ "liveweer": [{"fout": "Vraag eerst een API-key op, zie http://weerlive.nl/delen.php"}]}
yet when I login on weerlive , it show me my API key

**Comment by golles** [comment]
Please reach out to the supplier via `post@weerlive.nl`, I guess they have a problem with API keys.

I also see that my remaining API calls sensor has been stuck to 299 since September 23rd.

<img width="1218" src="https://github.com/user-attachments/assets/0b7f4437-d98e-4a2c-9aec-c0833b7e1366">

**Comment by jeroen94704** [comment]
I initially thought I had the same issue, but it turns out it takes a while after activation before the API key is usable. It actually says so in the email I got, although it took longer than the 5-10 minutes they mention. Not sure if that is the same for you as well, but at least in my case it started working fine after half an hour or so.
