### ISSUE TITLE
Request to add sensor for Nederlandse vliegveldverwachtingen

### ISSUE THREAD

**Issue by alenkab** [golles/ha-knmi#163]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The request

Would be awesome if you could add the text in https://www.knmi.nl/nederland-nu/luchtvaart/vliegveldverwachtingen as a sensor. Even better if it's one sensor per airport code.

**Comment by golles** [comment]
This component makes use of the weerlive API, https://weerlive.nl/delen.php and that doesn't support those
