### ISSUE TITLE
Alarm always 1?

### ISSUE THREAD

**Issue by EvertJob** [golles/ha-knmi#17]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

Hi,

Klopt het dat `alarm` altijd 1 is tenzij het hele land 'code groen' is? De twee bovenste steden hebben op het moment van schrijven geen weer alarm maar volgens ha-knmi wel. Klopt dit?

`{ "liveweer": [{"plaats": "groningen", "temp": "7.9", "gtemp": "4.2", "samenv": "Geheel bewolkt", "lv": "81", "windr": "NW", "windrgr": "315", "windms": "7", "winds": "4", "windk": "13.6", "windkmh": "25.2", "luchtd": "1005.4", "ldmmhg": "754", "dauwp": "4", "zicht": "16", "verw": "Onstuimig met aan zee eerst nog een stormachtige wind, morgen minder wind", "sup": "08:16", "sunder": "17:17", "image": "bewolkt", "d0weer": "bewolkt", "d0tmax": "7", "d0tmin": "2", "d0windk": "4", "d0windknp": "14", "d0windms": "7", "d0windkmh": "26", "d0windr": "NW", "d0windrgr": "315", "d0neerslag": "4", "d0zon": "12", "d1weer": "regen", "d1tmax": "9", "d1tmin": "4", "d1windk": "3", "d1windknp": "10", "d1windms": "5", "d1windkmh": "19", "d1windr": "W", "d1windrgr": "270", "d1neerslag": "90", "d1zon": "10", "d2weer": "halfbewolkt", "d2tmax": "9", "d2tmin": "6", "d2windk": "3", "d2windknp": "8", "d2windms": "4", "d2windkmh": "15", "d2windr": "NW", "d2windrgr": "315", "d2neerslag": "40", "d2zon": "30", "alarm": "1", "alarmtxt": "De code oranje is beeindigd. Wel komen met uitzondering van het noordoosten van het land nog zware windstoten van 75-100 km/u voor, hiervoor is code geel van kracht. Hierdoor kan schade en gevaar ontstaan als gevolg van omvallende bomen en rondvliegende voorwerpen.  De windstoten komen uit een noordwestelijke richting. In de loop van de middag neemt de wind geleidelijk af.     Opgesteld door het KNMI op: maandag 31 januari 2022 12:06 uur  EXTREEM WEER BEEINDIGD maandag 31 januari 2022 12:06 uur"}]}`

`{ "liveweer": [{"plaats": "Assen", "temp": "7.8", "gtemp": "3.8", "samenv": "Geheel bewolkt", "lv": "79", "windr": "NW", "windrgr": "315", "windms": "8", "winds": "5", "windk": "15.6", "windkmh": "28.8", "luchtd": "1005.6", "ldmmhg": "754", "dauwp": "4", "zicht": "19", "verw": "Onstuimig met aan zee eerst nog een stormachtige wind, morgen minder wind", "sup": "08:16", "sunder": "17:17", "image": "bewolkt", "d0weer": "bewolkt", "d0tmax": "7", "d0tmin": "2", "d0windk": "4", "d0windknp": "14", "d0windms": "7", "d0windkmh": "26", "d0windr": "NW", "d0windrgr": "315", "d0neerslag": "4", "d0zon": "12", "d1weer": "regen", "d1tmax": "9", "d1tmin": "4", "d1windk": "3", "d1windknp": "10", "d1windms": "5", "d1windkmh": "19", "d1windr": "W", "d1windrgr": "270", "d1neerslag": "90", "d1zon": "10", "d2weer": "halfbewolkt", "d2tmax": "9", "d2tmin": "6", "d2windk": "3", "d2windknp": "8", "d2windms": "4", "d2windkmh": "15", "d2windr": "NW", "d2windrgr": "315", "d2neerslag": "40", "d2zon": "30", "alarm": "1", "alarmtxt": "De code oranje is beeindigd. Wel komen met uitzondering van het noordoosten van het land nog zware windstoten van 75-100 km/u voor, hiervoor is code geel van kracht. Hierdoor kan schade en gevaar ontstaan als gevolg van omvallende bomen en rondvliegende voorwerpen.  De windstoten komen uit een noordwestelijke richting. In de loop van de middag neemt de wind geleidelijk af.     Opgesteld door het KNMI op: maandag 31 januari 2022 12:06 uur  EXTREEM WEER BEEINDIGD maandag 31 januari 2022 12:06 uur"}]}`

The two 

`{ "liveweer": [{"plaats": "utrecht", "temp": "5.8", "gtemp": "1.2", "samenv": "Lichte regen", "lv": "86", "windr": "NW", "windrgr": "315", "windms": "8", "winds": "5", "windk": "15.6", "windkmh": "28.8", "luchtd": "1010.4", "ldmmhg": "758", "dauwp": "3", "zicht": "6", "verw": "Onstuimig met aan zee eerst nog een stormachtige wind, morgen minder wind", "sup": "08:18", "sunder": "17:26", "image": "buien", "d0weer": "bewolkt", "d0tmax": "6", "d0tmin": "2", "d0windk": "5", "d0windknp": "17", "d0windms": "9", "d0windkmh": "31", "d0windr": "NW", "d0windrgr": "315", "d0neerslag": "8", "d0zon": "4", "d1weer": "regen", "d1tmax": "9", "d1tmin": "4", "d1windk": "3", "d1windknp": "10", "d1windms": "5", "d1windkmh": "19", "d1windr": "W", "d1windrgr": "270", "d1neerslag": "90", "d1zon": "10", "d2weer": "halfbewolkt", "d2tmax": "9", "d2tmin": "6", "d2windk": "3", "d2windknp": "8", "d2windms": "4", "d2windkmh": "15", "d2windr": "NW", "d2windrgr": "315", "d2neerslag": "40", "d2zon": "30", "alarm": "1", "alarmtxt": "De code oranje is beeindigd. Wel komen met uitzondering van het noordoosten van het land nog zware windstoten van 75-100 km/u voor, hiervoor is code geel van kracht. Hierdoor kan schade en gevaar ontstaan als gevolg van omvallende bomen en rondvliegende voorwerpen.  De windstoten komen uit een noordwestelijke richting. In de loop van de middag neemt de wind geleidelijk af.     Opgesteld door het KNMI op: maandag 31 januari 2022 12:06 uur  EXTREEM WEER BEEINDIGD maandag 31 januari 2022 12:06 uur"}]}`

`{ "liveweer": [{"plaats": "nijmegen", "temp": "5.4", "gtemp": "1", "samenv": "Motregen en regen", "lv": "88", "windr": "NW", "windrgr": "315", "windms": "7", "winds": "4", "windk": "13.6", "windkmh": "25.2", "luchtd": "1010.0", "ldmmhg": "758", "dauwp": "3", "zicht": "5", "verw": "Onstuimig met aan zee eerst nog een stormachtige wind, morgen minder wind", "sup": "08:15", "sunder": "17:25", "image": "regen", "d0weer": "bewolkt", "d0tmax": "7", "d0tmin": "2", "d0windk": "5", "d0windknp": "17", "d0windms": "9", "d0windkmh": "31", "d0windr": "NW", "d0windrgr": "315", "d0neerslag": "8", "d0zon": "8", "d1weer": "regen", "d1tmax": "9", "d1tmin": "4", "d1windk": "3", "d1windknp": "10", "d1windms": "5", "d1windkmh": "19", "d1windr": "W", "d1windrgr": "270", "d1neerslag": "90", "d1zon": "10", "d2weer": "halfbewolkt", "d2tmax": "9", "d2tmin": "6", "d2windk": "3", "d2windknp": "8", "d2windms": "4", "d2windkmh": "15", "d2windr": "NW", "d2windrgr": "315", "d2neerslag": "40", "d2zon": "30", "alarm": "1", "alarmtxt": "De code oranje is beeindigd. Wel komen met uitzondering van het noordoosten van het land nog zware windstoten van 75-100 km/u voor, hiervoor is code geel van kracht. Hierdoor kan schade en gevaar ontstaan als gevolg van omvallende bomen en rondvliegende voorwerpen.  De windstoten komen uit een noordwestelijke richting. In de loop van de middag neemt de wind geleidelijk af.     Opgesteld door het KNMI op: maandag 31 januari 2022 12:06 uur  EXTREEM WEER BEEINDIGD maandag 31 januari 2022 12:06 uur"}]}`

### What version of this integration has the issue?

1.1.6

### What version of Home Assistant Core has the issue?

core-2021.12.10

**Comment by golles** [comment]
Hi @EvertJob, It indeed looks like that and sadly this isn't something I can fix.

Like you mentioned, this is in the API from weerlive.
I myself sent them an email about that some time ago, but I think it's a good idea if you contact them as well -> post@weerlive.nl

Thanks
