### ISSUE TITLE
Integratie ondersteunt geen configuratie via de UI

### ISSUE THREAD

**Issue by Koosdezwart** [golles/ha-knmi#19]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

Foutmelding, wanneer de KNMI integratie wordt toegevoegd:

"Deze intergratie ondersteunt geen configuratie via de UI. Als u deze link van de homeassitant website heeft gevolgd, zorg er dan voor dat u de nieuwste versie van Home assistant draait."

core versie 2022.3.8
supervisor 2022.03.5
host OS 7.5

### What version of this integration has the issue?

1.1.7

### What version of Home Assistant Core has the issue?

core-2022.3.8

**Comment by golles** [comment]
How did you install this component?
It looks like you're missing some files, like `config_flow.py`

**Comment by Koosdezwart** [comment]
Hello Sander

Hereby my copied files

***@***.***



Regards,
koos


________________________________
Van: Sander ***@***.***>
Verzonden: Tuesday, March 29, 2022 11:24:01 PM
Aan: golles/ha-knmi ***@***.***>
CC: Koosdezwart ***@***.***>; Author ***@***.***>
Onderwerp: Re: [golles/ha-knmi] Integratie ondersteunt geen configuratie via de UI (Issue #19)


How did you install this component?
It looks like you're missing some files, like config_flow.py

**Comment by Koosdezwart** [comment]
And from my logbook
***@***.***
Van: Koos de ***@***.***>
Verzonden: woensdag 30 maart 2022 21:28
Aan: ***@***.***>
Onderwerp: RE: [golles/ha-knmi] Integratie ondersteunt geen configuratie via de UI (Issue #19)

Hello Sander

Hereby my copied files

***@***.***


Regards,
koos



Van: Sander ***@***.***>
Verzonden: Tuesday, March 29, 2022 11:24:01 PM
Aan: golles/ha-knmi ***@***.***>
CC: Koosdezwart ***@***.***>; Author ***@***.***>
Onderwerp: Re: [golles/ha-knmi] Integratie ondersteunt geen configuratie via de UI (Issue #19)


How did you install this component?
It looks like you're missing some files, like config_flow.py

**Comment by golles** [comment]
Hi Koos, I think something went wrong with your previous messages. 
Can you provide a list of all files in the `knmi` folder?
Also, can you provide the content of the `home-assistant.log`?

**Comment by Koosdezwart** [comment]
Hello,

I send some screenshots the last time but hereby a list of files.

Within the directory config\custom_components\knmi
_init_py
Api.pi
Binary_sensor.py
Config_flow.py
Const.py
Entity.py
Manifest.json
Sensor.py
Weather.py

+ the folder translations
en.json
nl.json

The log files
Logger:homeassistant.config_entries
Source: config_entries.py:745

Regards,
Koos

Error occurred loading configuration flow for integration knmi: No module named custom_components.knmi.config_flow


Van: Sander ***@***.***>
Verzonden: zondag 3 april 2022 20:40
Aan: golles/ha-knmi ***@***.***>
CC: Koosdezwart ***@***.***>; Author ***@***.***>
Onderwerp: Re: [golles/ha-knmi] Integratie ondersteunt geen configuratie via de UI (Issue #19)


Hi Koos, I think something went wrong with your previous messages.
Can you provide a list of all files in the knmi folder?
Also, can you provide the content of the home-assistant.log?

**Comment by golles** [comment]
> I send some screenshots the last time but hereby a list of files.

I think because you're answering by email and not on GitHub, no images got added. (I didn't even know you could reply by email directly :-) )

> Within the directory config\custom_components\knmi 
> _init_py
> Api.pi
> Binary_sensor.py
> Config_flow.py
> Const.py
> Entity.py
> Manifest.json
> Sensor.py
> Weather.py

Is this exactly how the files are named for you? 
They should be named like this:
```
__init__.py  
api.py  
binary_sensor.py  
config_flow.py  
const.py  
entity.py  
manifest.json 
sensor.py  
translations  (folder with en.json nl.json)
weather.py
```

**Comment by Koosdezwart** [comment]
The exact file names.

__init__.py
api.py
binary_sensor.py
config_flow.py
const.py
entity.py
manifest.json
sensor.py
weather.py

Sorry that I reply on E-mail ☹

Van: Sander ***@***.***>
Verzonden: woensdag 6 april 2022 00:06
Aan: golles/ha-knmi ***@***.***>
CC: Koosdezwart ***@***.***>; Author ***@***.***>
Onderwerp: Re: [golles/ha-knmi] Integratie ondersteunt geen configuratie via de UI (Issue #19)


I send some screenshots the last time but hereby a list of files.

I think because you're answering by email and not on GitHub, no images got added. (I didn't even know you could reply by email directly :-) )

Within the directory config\custom_components\knmi
_init_py
Api.pi
Binary_sensor.py
Config_flow.py
Const.py
Entity.py
Manifest.json
Sensor.py
Weather.py

Is this exactly how the files are named for you?
They should be named like this:

__init__.py

api.py

binary_sensor.py

config_flow.py

const.py

entity.py

manifest.json

sensor.py

translations  (folder with en.json nl.json)

weather.py
