### ISSUE TITLE
Add "precipitation_chance"

### ISSUE THREAD

**Issue by erikmolenaarnl** [golles/ha-knmi#22]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The request

Hi,

Could you please add "precipitation_chance"? Would be awesome. Thanks for all the hard work.

![image](https://user-images.githubusercontent.com/22014267/171839482-e6c6a1c3-96f0-4a46-b188-da56a0647a0a.png)

**Comment by golles** [comment]
Thank you @erikmolenaarnl,
After reading the documentation, https://developers.home-assistant.io/docs/core/entity/weather/
I realized I mixed up `precipitation` and `precipitation_probability` in the forecast.

Not sure where `precipitation_chance` is coming from, maybe I'm missing something?

**Comment by golles** [comment]
Fix is released in version `1.1.8` https://github.com/golles/ha-knmi/releases/tag/1.1.8
