### ISSUE TITLE
Adding forecast text

### ISSUE THREAD

**Issue by WouterKr** [golles/ha-knmi#3]
First of all thanks for this integration!

Is it possible to add the forecast text of 'weerlive'?
I would like to use it for pronouncing the weather forecast.
In the reply of the url it looks like:

"verw": "Enkele buien, vanavond in het noorden zware windstoten",

Thanks in advance
Regards,
Wouter

**Comment by golles** [comment]
Yes, I can add it as a new sensor, the weather entity doesn't allow me to add extra fields as far as I know

**Comment by WouterKr** [comment]
That would be I nice addition. Thanks

**Comment by golles** [comment]
Hi @WouterKr I've updated the component with some new sensors, you might need to remove the current integration and re-add it. As I had to change the logic for unique id's.

**Comment by WouterKr** [comment]
**@golles** Hi, Thanks for the effort! Removed the previous version and re-installed the new one.
Seeing some more entities and the forecast (korte_dagverwachting), great. Used it already to announced the current forecast.

For me this issue can be closed.

**Comment by golles** [comment]
Great and thanks for the quick feedback
