### ISSUE TITLE
Error in statistics

### ISSUE THREAD

**Issue by haaino** [golles/ha-knmi#33]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

Hi,

I'm getting the following error messages in developer tools -> statistics for the entities: sensor.knmi_knmi_dauwpunt and sensor.knmi_knmi_gevoelstemperatuur

----
Unsupported state class in statistics

The state class of this entity, is not supported.
Statistics can not be generated until this entity has a supported state class.

If this state class was provided by an integration, this is a bug. Please report an issue.

If you have set this state class yourself, please correct it. The different state classes and when to use which can be found in the developer documentation.

----
<img width="1679" alt="Screenshot 2022-07-15 at 9 21 04 " src="https://user-images.githubusercontent.com/98317278/179172960-d5bdf54f-a70b-4881-8860-4b4b487ff569.png">

as a recorder I use MariaDB.

Perhaps I'm doing something, please let me know.

### What version of this integration has the issue?

1.1.11

### What version of Home Assistant Core has the issue?

2022.7.5

**Comment by golles** [comment]
I noticed this as well earlier this week, #31 should fix this.
I need to do some verification of that change and hope to have it merged and released during the weekend

**Comment by golles** [comment]
Hi @haaino 
Version `1.2.0` https://github.com/golles/ha-knmi/releases/tag/1.2.0 has just been released and should fix this issue.
Feel free to reopen if the issue still persists.

Please star this repository if you like this integration, this recognition drives me to work on this and keep on improving it :-)
