### ISSUE TITLE
Forecast extension 

### ISSUE THREAD

**Issue by haaino** [golles/ha-knmi#35]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The request

Hi,

I noticed that there is pressure attribute in the current weather, but it is not in the forecast. Is it possible to extend the forecast attributes with this as well? I have no idea if this is possible. 

Same applies for humidity, visibility and precipitation

Thank you already for all the good work!

**Comment by golles** [comment]
Sorry, all the fields you would like to get added are not available in this API, see https://weerlive.nl/delen.php on the Parameters tab for a list of which data is available.

I think that all the data that is available in the API is consumed in this integration, besides the town name and anything in a different unit

**Comment by haaino** [comment]
Thank you for your help
