### ISSUE TITLE
Perhaps a parsing error????

### ISSUE THREAD

**Issue by haaino** [golles/ha-knmi#36]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

Hi,

Knmi has issued a warning. I noticed the following in this warning 

—

temperaturen van 32-36Â°C 

—

I have no idea if this is a parsing issue or knmi issue. What do you think?

### What version of this integration has the issue?

1.2.20

### What version of Home Assistant Core has the issue?

2022.7.5

**Comment by golles** [comment]
Hi, I noticed this yesterday as well, It's not a parsing issue, as this is coming directly from the response, I've also no idea what the `Â` is supposed to be...

```json
"alarmtxt": "Waarschuwing Maandag en vooral dinsdag zeer warm. Dinsdag in het midden en zuiden zeer hoge temperaturen  Vandaag en morgen wordt het tropisch warm. Daarom is het Nationaal hitteplan (RIVM) en code geel van kracht voor het hele land.  Vandaag worden er temperaturen verwacht tussen 30 en 35Â°C.  Morgen zijn in het noorden temperaturen van 32-36Â°C mogelijk. In het midden en zuiden geldt vanaf het einde van de dinsdagochtend tot in de avond code oranje voor zeer hoge temperaturen, met maximumtemperaturen van 38-39Â°C.  Woensdag wordt de warmte verdreven. In het oosten kan het dan nog 30Â°C worden.  (Extreme) hitte kan gevolgen hebben voor de gezondheid. Met name voor ouderen, kleine kinderen en mensen met een kwetsbare gezondheid maar ook voor gezonde mensen.    Volgend bericht uiterlijk: maandag 18 juli 2022 14:30 uur"
```

**Comment by golles** [comment]
Reopening, I'd like to contact the provider about this.

**Comment by golles** [comment]
I had contact with the provider, they said it shouldn't happen on their side.
Please re-open this issue if you see it again.

**Comment by golles** [comment]
It's back for tomorrow's warning, I've sent an email to the provider

**Comment by golles** [comment]
They fixed it
