### ISSUE TITLE
Waarschuwing per gebied

### ISSUE THREAD

**Issue by haaino** [golles/ha-knmi#39]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The request

Hoi,

Ik weet niet of het mogelijk is, maar nu ontvang ik na alle tevredenheid in 1 waarschuwing een totaal overzicht van alle waarschuwingen over heel NL.

Is het ook mogelijk om waarschuwingen te krijgen voor bijv. 1 provincie?

Mvg,
haaino

**Comment by golles** [comment]
Hi, hier is niks aan te doen. 
Je kunt eventueel je verzoek bij de API provider neerleggen, deze kun je mailen op [post@weerlive.nl](mailto:post@weerlive.nl)
