### ISSUE TITLE
Current condition

### ISSUE THREAD

**Issue by dutch-erik** [golles/ha-knmi#48]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

I don't think below is the correct 'current condition'.
`d0weer` is the forecast for today and isn't changing during the day, while `image` is in my eyes the 'current condition' and changing during the day.

weather.py
```
    @property
    def condition(self) -> str | None:
        """Return the current condition."""
        if self.coordinator.get_value("d0weer") is not None:
            return CONDITIONS_MAP[self.coordinator.get_value("d0weer")]
        return None

```

### What version of this integration has the issue?

1.3.1

### What version of Home Assistant Core has the issue?

2022.11.2

**Comment by golles** [comment]
Hi @dutch-erik I think your thought is correct, I've got a PR ready with the change. I'll test that branch for a day and if tomorrow everything is fine, I'll merge it and release that.
Thank you!

**Comment by dutch-erik** [comment]
I did have a look at the branch and although I'm not a programmer (I wish a was) I don't think it will update when condition changes. My thought is just based on comparing the code with f.e. Buienradar or Weatherbit. However, I can't tell you what should be changed or added.

**Comment by golles** [comment]
I'm not sure why you mention in your first and second posts about the condition not being updated. In the following screenshot, you can see that both `1.3.1` and the version of this `PR` is changing. I switched yesterday around 1930:

<img width="1403" alt="Scherm­afbeelding 2022-11-16 om 17 54 41" src="https://user-images.githubusercontent.com/2211503/202243911-231445a1-f62c-42fd-b67f-340e7e86ae5a.png">

I'm planning to release `1.3.2` in a bit

**Comment by dutch-erik** [comment]
I was mentioning it because here it looks like it only changes at midnight of after restart/reboot.
I installed latest version and keep an eye on it. ;)
