### ISSUE TITLE
Forecast 5 days

### ISSUE THREAD

**Issue by silvanverschuur** [golles/ha-knmi#5]
I've installed the KNMI integration but I only see 3 days (today, and the next 2 days). All other weather integrations show 5 days. I don't know if this is a limitation of the KNMI API?

When I visit the https://weerlive.nl/ website I get 5 days forecast. Is this something you can add/modify?

**Comment by golles** [comment]
Sadly the free API does only give 2 days forecast, see https://weerlive.nl/delen.php `Parameters` tab.
I need to update the docs to make this more clear I guess

**Comment by golles** [comment]
I've updated the readme, closing this issue
