### ISSUE TITLE
wolkennacht

### ISSUE THREAD

**Issue by haaino** [golles/ha-knmi#55]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

Encountered the following in log file 

### What version of this integration has the issue?

1.3.3

### What version of Home Assistant Core has the issue?

HA 2022.11.3

### Home Assistant log

```shell
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/knmi/weather.py:103 
Integration: KNMI (documentation, issues) 
First occurred: 04:14:57 (480 occurrences) 
Last logged: 08:14:28

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 813, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 832, in state
    return self.condition
  File "/config/custom_components/knmi/weather.py", line 103, in condition
    return CONDITIONS_MAP[self.coordinator.get_value("image")]
KeyError: 'wolkennacht'
```

**Comment by golles** [comment]
I'm getting a little confused, I've recently removed `wolkennacht` as it's not documented on the website: https://weerlive.nl/delen.php

I'll restore it for now and contact the supplier in the mean time.

**Comment by golles** [comment]
This has been fixed in 1.3.4, similar issues will be handled better, now with an error log instead of a error trace:
`2022-11-20 07:27:39.875 ERROR (MainThread) [custom_components.knmi] Weather condition wolkennacht (for image) is unknown, please raise a bug`

**Comment by haaino** [comment]
I wonder if I could close this issue?

**Comment by golles** [comment]
I want to keep this until I've heard from the supplier. I've sent them a reminder mail today

**Comment by golles** [comment]
Still no reply. Will close this now
