### ISSUE TITLE
minimum verwachting is eigenlijk van gister

### ISSUE THREAD

**Issue by roolootje** [golles/ha-knmi#60]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

leuke integratie! 
het viel me op dat in de knmi card de minimum temperatuur van afgelopen nacht staat, terwijl je denk ik juist zou willen zien wat het komende nacht gaat worden. Nu staat bv actuele temp van -3,5oC met daar onder 2oC -3oC terwijl bij de verwachting voor morgen -7 staat, wat het dus zo gaat worden.

### What version of this integration has the issue?

1.3.5

### What version of Home Assistant Core has the issue?

2022.12.6

**Comment by golles** [comment]
Is dit niet exact wat er bij [known limitations](https://github.com/golles/ha-knmi/blob/main/README.md#known-limitations) nummer 2 beschreven staat?
