### ISSUE TITLE
Language parameter widgets

### ISSUE THREAD

**Issue by TWFpa2Vs** [golles/ha-knmi#66]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The request

It would be nice if you could add a language parameter so the language of HA itself can be different from the actual widgets.
I like my HA in English but my widgets in Dutch :)

**Comment by golles** [comment]
I don't think this makes a lot of sense, the whole integration is based on HA standards, so it integrates really well and is language-independent. If you want to have Dutch

If you really want this, you could create a template weather entity and translate the condition yourself using the `condition_template` into the templates, https://www.home-assistant.io/integrations/weather.template/ However I think that that will break any weather card, as the state internally for the cards should be in English.
