### ISSUE TITLE
binary_sensor alert won't change icon (color)

### ISSUE THREAD

**Issue by Mariusthvdb** [golles/ha-knmi#71]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

seems the icon of the binary_sensor does not change depending on state.

Trying to set it to another device_class in the UI doesn't not work either.

always showing the alert state with exclamation mark:

<img width="506" alt="Scherm­afbeelding 2023-02-14 om 16 56 21" src="https://user-images.githubusercontent.com/33354141/218790011-ca05260a-5c8f-4c69-aa0f-7b8a55044ebd.png">

<img width="567" alt="Scherm­afbeelding 2023-02-14 om 16 56 28" src="https://user-images.githubusercontent.com/33354141/218790017-94a1b9f0-5d82-48c8-83fd-d5c97ea526e8.png">

while a safe icon of this device_class should show:

<img width="594" alt="Scherm­afbeelding 2023-02-14 om 16 57 35" src="https://user-images.githubusercontent.com/33354141/218790273-a829f2b6-9162-4577-9ed7-78a0b139cf71.png">

also adding to this issue, is that even though

```
state_color: true
```
is set in the entities card, the binary_sensor does not change color to alert color as it should. The more-info does not show either, so it's an integration issue, not a frontend issue.

compare:

<img width="501" alt="Scherm­afbeelding 2023-02-14 om 16 59 53" src="https://user-images.githubusercontent.com/33354141/218790872-3f97ccda-6776-40a0-8569-cb5bf1bc9b22.png">

and more info:

<img width="574" alt="Scherm­afbeelding 2023-02-14 om 17 00 17" src="https://user-images.githubusercontent.com/33354141/218791000-5f09a620-39d4-4150-928a-d2328481f09b.png">

### What version of this integration has the issue?

1.3.7

### What version of Home Assistant Core has the issue?

2023.2.4

### Diagnostics

[config_entry-knmi-c25fc6a1ec4907582d45a36a2dc3df54.json.txt](https://github.com/golles/ha-knmi/files/10734428/config_entry-knmi-c25fc6a1ec4907582d45a36a2dc3df54.json.txt)

**Comment by golles** [comment]
I liked this custom icon more than the standard icon, but this caused this logic to not be taken into account
