### ISSUE TITLE
Weerwaarschuwing niet ingeladen

### ISSUE THREAD

**Issue by avlimburg** [golles/ha-knmi#77]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

Via de API komt er bij een weerwaarschuwing ook een txt door. De plugin neemt die niet over, geeft alleen bericht weer "Onveilig" terwijl in de API het volgende staat:  "alarmtxt": "Vanaf halverwege de avond kan het in het midden en noorden van het land glad worden door bevriezing van natte weggedeelten. Vanaf het einde van de nacht gaat het in het zuiden enig tijd sneeuwen waardoor het ook daar plaatselijk glad kan worden. In de Limburgse heuvels kan meer dan 5 cm vallen. Woensdagmiddag is de gladheid tijdelijk voorbij.  In de nacht naar donderdag kan het opnieuw plaatselijk glad worden door bevriezing van natte weggedeelten, in het zuiden van het land opnieuw door (natte) sneeuw.  Verkeer en buitenactiviteiten hinder ondervinden van de gladheid."}]}

### What version of this integration has the issue?

1.3.8

### What version of Home Assistant Core has the issue?

2023.03.1

**Comment by golles** [comment]
Deze text is te vinden in de attributen van de waarschuwingsentity, zie:

<img width="552" alt="Scherm­afbeelding 2023-03-07 om 19 27 25" src="https://user-images.githubusercontent.com/2211503/223516226-79c25c2c-4b01-4724-825d-23c4e595bbd9.png">
