### ISSUE TITLE
Too many api calls

### ISSUE THREAD

**Issue by Constant-Vathorst** [golles/ha-knmi#81]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

All sensors have become unavailable. Looking at log, it says "Error in API! - Exceeded Daily Limit".
Is there some way one can select how often the sensors are updated?
KNMI says the limit is 300 per day. Maybe you can add a frequecy, which has to be 5 minutes minimal?

### What version of this integration has the issue?

1.3.8

### What version of Home Assistant Core has the issue?

2023.4.4

### Home Assistant log

```shell
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.knmi
Source: custom_components/knmi/api.py:33
Integration: KNMI (documentation, issues)
First occurred: 12:35:44 (30 occurrences)
Last logged: 14:29:11

Error in API! - Exceeded Daily Limit
```

**Comment by golles** [comment]
The update interval is at this moment hardcoded to every 5 minutes (300 seconds), https://github.com/golles/ha-knmi/blob/main/custom_components/knmi/const.py#L17

I didn't make this configurable, as this value would consume 288 calls per day, which is within the limit.
Are you using the integration multiple times, with the same API key? Or have you done quite some restarts of your HA?

I've been working on a huge refactor #80 and I've checked the API again this week to see if it provides any information about the limit, but sadly it doesn't.

**Comment by Constant-Vathorst** [comment]
> The update interval is at this moment hardcoded to every 5 minutes (300 seconds), https://github.com/golles/ha-knmi/blob/main/custom_components/knmi/const.py#L17
> 
> I didn't make this configurable, as this value would consume 288 calls per day, which is within the limit. Are you using the integration multiple times, with the same API key? Or have you done quite some restarts of your HA?
> 
> I've been working on a huge refactor #80 and I've checked the API again this week to see if it provides any information about the limit, but sadly it doesn't.

Thank you for your response. I did indeed restart home assistance quite a lot today (installing on new machine). That must be the reason.
5 minutes (288 calls a day,) would have been my suggestion as well. It will then come back online tomorrow again. :-)

**Comment by golles** [comment]
Yes, tomorrow it will work again :-)
