### ISSUE TITLE
Safe?

### ISSUE THREAD

**Issue by haaino** [golles/ha-knmi#85]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

Hi,

Yesterday there was code yellow and orange.

In previous versions the status "safe" status changed. To my surprise this did not happen. Was I the only one with this observation?

I wonder weather this was expected behavior or did KNMI itself did not "toggle" a status somewhere?

Best regards,
Haaino

### Integration version

1.5.0

### Home Assistant version

HA 2.23.6.2

### Python version

3.11

### Home Assistant log

```shell
Hi,

Yesterday there was code yellow and orange.

In previous versions the status "safe" status changed. To my surprise this did not happen. Was I the only one with this observation?

I wonder weather this was expected behavior or did KNMI itself did not "toggle" a status somewhere?

Best regards,
Haaino
```

**Comment by golles** [comment]
Hi, I noticed this as well during the thunderstorm on Tuesday.

At the moment I do have a warning. You can verify that by downloading your diagnostics file (which is also asked to share in the issue template). In that json file, under `data` -> `data` you can see the values from weerlive. If it states `"alarm": "0"` and/or `"alarmtxt": ""`, there is nothing I can do and not a bug pf this component, in that case, the API isn't sharing it, bests to contact the supplier: [post@weerlive.nl](mailto:post@weerlive.nl) (note, I'm not affiliated with them).

**Comment by haaino** [comment]
Also got a warning today. Let assume it wad a glitch for the moment and monitor if this happens again.
