### ISSUE TITLE
request for "gevoelstemperatuur"

### ISSUE THREAD

**Issue by turnmike2** [golles/ha-knmi#9]
Hi, 
In the datastream coming from KNMI also a piece of data for "gevoelstemperatuur" is available.
As I am not quite known with merge requests, I kindly ask to take a look into the following addon:

In const.py to add in "SENSORS:"
    {"name": "Gevoelstemp", "unit": "°C", "icon": "mdi:thermometer", "key": "gtemp"},

and in weather.py section "class KnmiWeather(KnmiEntity, WeatherEntity):"

    @property
    def gtemperature(self):
        """Return the temperature."""
        return float(self.coordinator.data["gtemp"])

    @property
    def gtemperature_unit(self):
        """Return the unit of measurement."""
        return TEMP_CELSIUS

This works for me quite well...

Thanks for looking.
Michel

**Comment by golles** [comment]
Thanks Michel, will pick this up soon!

**Comment by turnmike2** [comment]
Hi @golles 

As my knowlegde about github is not so high, I was not able  to get the branch from the site... sorry for that.
But instead I copied the 4 updated files manually ;-) The last 24 hours are running with the updated files.
So at this moment running version 1.1.4. And it looks OK!

As far as I can see right now everthing works accordingly.
Thanks.

**Comment by golles** [comment]
Good to hear, I made a few more updates and merged it.
`Dauwpunt` and `gevoelstemperatuur` are now also added in the long term statistics of HA
