### ISSUE TITLE
weather.knmi_huis is using a forecast attribute on an instance of WeatherEntity

### ISSUE THREAD

**Issue by Mitch73-2** [golles/ha-knmi#90]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

Logger: homeassistant.components.weather
Source: components/weather/init.py:339
Integration: Weer (documentation, issues)
First occurred: 10:12:35 (1 occurrences)
Last logged: 10:12:35

custom_components.knmi.weather::weather.knmi_huis is using a forecast attribute on an instance of WeatherEntity, this is deprecated and will be unsupported from Home Assistant 2024.3. Please report it to the custom integration author.

### Integration version

1.5.0

### Home Assistant version

core-2023.9.0b3

### Python version

3.11.5

### Home Assistant log

```shell
weather.knmi_huis is using a forecast attribute on an instance of WeatherEntity, this is deprecated and will be unsupported from Home Assistant 2024.3. Please report it to the custom integration author.
```

**Comment by golles** [comment]
Duplicate #87

**Comment by golles** [comment]
Released: https://github.com/golles/ha-knmi/releases/tag/1.6.0
