### ISSUE TITLE
Support depreciated forecast attribute until 2024.3

### ISSUE THREAD

**Issue by TheFes** [golles/ha-knmi#93]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The request

I see you updated the weather entity and are now using the new way to store the forecast data. However, I (and with me probably a lot of other people) are still using the old forecast attribute for templating.
For example, I have a template weather entity in which I combine an weather forecasts to an average one. This is currently not possible with the "hidden" forecasts.
So with the updated version of the KNMI weather entity, I'm unable to include it.

Therefor it would be nice if the old-style forecast could still be included until it is really removed in 2024.3

**Comment by spasma** [comment]
if you don't care for the new integration (for now), You can select and install v1.5.0 in the HACS interface.

**Comment by TheFes** [comment]
Sure, but all core weather integrations also support both, I would also be unable to update to add new improvements or to have bugs fixed until there is a viable solution for the template weather.

**Comment by golles** [comment]
I knew there would be issues due to this, please join the conversation here, https://github.com/golles/ha-knmi/issues/87#issuecomment-1710486393
(I'll leave this issue open for a bit so others can find it easier)

**Comment by pathia** [comment]
+1 for the dual support (deprecated + new way).
This way people(me 😄 ) can rewrite their automations and stuff without them being broken meanwhile.
How else are we suppose to migrate without lots of downtime of our automations.

**Comment by golles** [comment]
Since it's relatively easy to pull the data from the new service I don't feel like restoring this logic back and removing it again in the future. My suggestion, for now, is to get the data from the new service or roll back to version `1.5.0`. The only difference between the 2 versions is this.
