### ISSUE TITLE
use KNMI API instead of weerlive

### ISSUE THREAD

**Issue by Mrten** [golles/ha-knmi#95]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The request

I'd just like to point out that the KNMI has an developer API at

https://developer.dataplatform.knmi.nl/apis

The documentation is fantastic and horrible at the same time, here are the available datasets for weather forecasts:

https://dataplatform.knmi.nl/group/weather-forecast

I've implemented the 'weather warnings' API for my job, it works quite nice. I have currently an open question if the usual forecasts are available over there.

https://dataplatform.knmi.nl/dataset/waarschuwingen-nederland-48h-1-0

**Comment by Mrten** [comment]
Well disregard that I suppose. I got an answer: https://dataplatform.knmi.nl/dataset/harmonie-arome-cy40-p2a-0-2 is the dataset you're looking for but it's a four times daily generated 1 GB zipfile that contains _all_ meteorological data (wind, dewpoint, temperature, rain, etc) for _all_ of the next 48 hours for _all_ of the Benelux in a GRIB format that was previously unknown to me but is a binary format for meteorological data.

No way that's practical for a single HomeAssistant installation to download or process.

**Comment by golles** [comment]
Oef that's indeed not very practical. 

I wasn't aware of this API, I've considered https://meteoserver.nl but since it's a paid service I'm not using that (and probably not many others). Looking back I should probably have called this custom_component weerlive instead of knmi.
Since a change or migration is going to be impossible, as it's a completely different service

**Comment by Mrten** [comment]
I've asked the KNMI if they would consider providing the data indexed on X,Y... Who knows :)

(the KNMI iOS app already shows that data)
